# Colonnes cibles de la couche Silver (staging.source_transformed).
# Les deux transforms (initial load et delta) projettent leur output sur ces colonnes,
# garantissant un schéma uniforme pour le MERGE incrémental.
TARGET_COLUMNS = [
    'code',
    'product_name',
    'brands',
    'product_quantity',
    'product_quantity_unit',
    'quantity',
    'serving_quantity',
    'serving_size',
    'categories_tags',
    'countries_tags',
    'ecoscore_score',
    'ecoscore_grade',
    'ingredients',
    'ingredients_n',
    'nutriscore_score',
    'nutriscore_grade',
    'front_url',
    'ingredients_url',
    'nutrition_url',
    'packaging_url',
    'energy_kcal_100g',
    'fat_100g',
    'saturated_fat_100g',
    'trans_fat_100g',
    'cholesterol_100g',
    'sodium_100g',
    'salt_100g',
    'carbohydrates_100g',
    'fiber_100g',
    'sugars_100g',
    'proteins_100g',
    'calcium_100g',
    'iron_100g',
    'potassium_100g',
]
